/*

389. Find the Difference

You are given two strings s and t.
String t is generated by random shuffling string s and then add one more letter at a random position.
Return the letter that was added to t.

Example 1:
Input: s = "abcd", t = "abcde"
Output: "e"

Explanation: 'e' is the letter that was added.

Example 2:
Input: s = "", t = "y"
Output: "y"

*/

class Solution {
    public char findTheDifference(String s, String t) {
        int sum1 = 0, sum2 = 0;

        for (int i = 0; i < s.length(); i++) {
            sum1 = sum1 + s.charAt(i);
        }

        for (int i = 0; i < t.length(); i++) {
            sum2 = sum2 + t.charAt(i);
        }
        return (char) (sum2 - sum1);
    }
}